# Generated by Django 5.2.4 on 2025-07-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_docxtpl', '0002_bookdetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='images1',
            field=models.FileField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
